### ISSUE TITLE
Use `usize` consistently for channel, input/output and length

### ISSUE THREAD

**Issue by b-ma** [orottier/web-audio-api-rs#122]
from #116 

> As a side note, we have a discrepancy with types here, i.e. number_channel: usize and length: usize, which should both be u32 if we strictly follow the spec. Also this is inconsistent with other places of the code (e.g. ConcreteBaseAudioContext). [...]
> 
> Not sure what we should decide though: unsigned long is usize or u32? As they are generally used as indexes, maybe usize would make more sens somehow but I'm not really sure of all the implications of such choice. My only opinion here is that we should be very consistent and apply the same rule everywhere. Maybe creating and maintaining a map of the correspondances somewhere would be helpful? (also we may have a similar problem with &[f32] and Vec<f32> at some places)

**Comment by orottier** [comment]
There's three integer quantities we are dealing with:

- channel (count and index)
- input/output port of nodes (count and index)
- buffer length (for offlineaudiocontext, audiobuffer, render quantum)

For all of these, `usize` seems most suitable from a Rust perspective. Typically that would be equivalent to a `u64` on modern platforms, which is a bit excessive but not really an issue either.

For channels, we're using both `u32` (in constructors mostly) and `usize`. This should be fixed.
For input/output port, we're using `u32` quite consistently in the public interface.
For length, we use `usize` consistently.

I'm inclined to use `usize` for all three of them.
Consistency is most important to me.
I'm not too worried we're are using `unsigned long long` instead of `unsigned long` and have a small spec deviation.

Agree @b-ma ?

**Comment by b-ma** [comment]
Yup agreed, sounds like the most simple and logical solution. 

Just as a side note, it seems the spec use `unsigned long long` only for `AudioWorklet::currentFrame` (cf. https://webaudio.github.io/web-audio-api/#dom-audioworkletglobalscope-currentframe), in this case we should maybe use a real `u64` to make sure to not fall into weird issues on 32 bit platforms (e.g. Raspberry Pi, etc.). Actually, I'm just realizing this value is not part of the `AudioProcessor::process` signature, maybe we should add it no?

**Comment by orottier** [comment]
Oof, good point. I will look into it, very important before v1 release
