### ISSUE TITLE
Implement `EventHandler` attributes

### ISSUE THREAD

**Issue by orottier** [orottier/web-audio-api-rs#219]
Search for `of type EventHandler` in https://webaudio.github.io/web-audio-api/ 

Simplest implementation is probably an `Option<Box<dyn Fn(Event)>>`

**Comment by b-ma** [comment]
I've started to think about it and to try some things, nothing really working and I'm doing things outside the lib to not mess around too much (I guess once we have the right approach it should quite straightforward to port into the lib).

I will try to make a working prototype these next days, or at least a failing one that would properly represent showing the different questions/problems I end with

**Comment by orottier** [comment]
Great.
Yeah, the `removeEventListener` is tricky. Let's see how far we can come without overcomplicating stuff

**Comment by b-ma** [comment]
Regarding your work on AudioRenderCapacity, I think it's maybe better to go with the simple `oneneded`, etc API, probably building the more advanced one on top of that would be feasible after, what do you think?

There is one thing I had in mind but I'm not sure it's the right approach, so your enlightenments would be welcome :) 
My idea was somehow to delegate all this to the context, so that we have only one thread that waits for incoming events from control thread with only one communication channel. But my impression is that it requires the have some book-keeping of the AudioNode ids in the control thread too. 

as pseudo code, would mean something like:
```
node.onended(func) {
    context.register_callback(node.id, type, func)
    // context store callback in some nested map: NodeId => EventType => Func
}

// on render thread
renderer.dispatch_event(type)
-> sends a { nodeId, type } message for the control / callback thread
```
Also that would mean that when the renderer are dropped, this would trigger some cleaning in the callback map

Not sure I'm clear, but do you think that's a good way to go?

**Comment by orottier** [comment]
It is probably easier to use many channels instead of one.
So when a `AudioBufferSourceNode` is created, set up a `onended_channel`. Put the `Sender` inside the renderer. The `Receiver` alongside an `Arc<Mutex<Callback>>` can be added to a new (singleton) struct `EventLoop` 
In a dedicated thread, the `EventLoop` can poll all receivers and run the callback when appropriate.
This requires very little bookkeeping so should be relatively simple, no?
Dropping a renderer could send a `None` value via the channel to let the `EventLoop` drop the callback

**Comment by orottier** [comment]
You can use https://docs.rs/crossbeam-channel/latest/crossbeam_channel/macro.select.html to poll all receivers concurrently in the EventLoop thread

**Comment by orottier** [comment]
So maybe you should just use a single channel. Use an ever increasing numerical id to select the right callback, and make sure the renderer ships the id alongside the payload. Payload should probably be an enum of a `Box<dyn Any>`

**Comment by orottier** [comment]
Alright, we have a very decent first implementation of the `onended` event handlers for `AudioScheduledSourceNode`s merged into `main`.

Next steps:

- [ ] how to cancel an event listener?
- [ ] unify interface with `AudioRenderCapacity::onupdate`
- [ ] API for events that come with a payload (not just a plain `Event`)

We need to figure these out before the v1 version lands. Or we should stick the event handlers behind an `unstable` flag

And implement:

- [x] ~~`onaudioprocess`~~ for deprecated `ScriptProcessor`
- [ ] `oncomplete` for `OfflineAudioContext`(not really needed when we only provide a synchronous interface..)
- [x] `onended` for `AudioScheduledSourceNode`
- [ ] `onprocessorerror` for `AudioWorkletNode` (todo, current API does not allow for it unless we set up a panic handler)
- [ ] `onsinkchange` for `AudioContext`
- [ ] `onstatechange` for `BaseAudioContext`
- [x] `onupdate` for `AudioRenderCapacity`
