### ISSUE TITLE
Sample rate high on ALSA

### ISSUE THREAD

**Issue by Jerboas86** [orottier/web-audio-api-rs#28]
context.sample_rate() displays a sample rate of 384 000 Hz on my ALSA system.
This default sample rate is coming from the CPAL default output config.

Possible solution: try to build a stream with a lower sample rate before defaulting into the CPAL default sample rate.

**Comment by orottier** [comment]
This is because we call [with_max_sample_rate](https://docs.rs/cpal/latest/cpal/struct.SupportedStreamConfigRange.html#method.with_max_sample_rate) on the SupportedStreamConfigRange in `io.rs`. We could try to use [with_sample_rate](https://docs.rs/cpal/latest/cpal/struct.SupportedStreamConfigRange.html#method.with_sample_rate) instead
