### ISSUE TITLE
AudioContext's decodeAudioData() doesn't return a Promise when a callback is not given.

### ISSUE THREAD

**Issue by Type1J** [orottier/web-audio-api-rs#300]
From what I can tell, this is already fixed, but there's been no release for a long time. I'll drop my polyfill that monkey patches this functionality into version `0.2.2`, which is what you get from `npm`, right now.

    import { AudioContext } from "web-audio-api";
    
    export function installPolyfill() {
      function decodeAudioData_polyfill(audioData, successCallback, errorCallback) {
        if (arguments.length > 1) {
          // Callback
          this.decodeAudioData(audioData, successCallback, errorCallback);
        } else {
          // Promise
          return new Promise((success, reject) => this.decodeAudioData_original(audioData, success, reject));
        }   
      }
      if (!AudioContext.prototype.decodeAudioData_original) {
        AudioContext.prototype.decodeAudioData_original = AudioContext.prototype.decodeAudioData;
        AudioContext.prototype.decodeAudioData = decodeAudioData_polyfill;
      }
    }

Please release sometime soon. Until then, please leave this issue open, so that someone having this problem can find this solution.

**Comment by b-ma** [comment]
Hey, 

It seems you are at the wrong place, this project is dedicated to a pure Rust implementation of the Web Audio API not a javascript one. We actually provide bindings to node-js, but the package is called [`node-web-audio-api`](https://www.npmjs.com/package/node-web-audio-api) and the repository is there [https://github.com/ircam-ismm/node-web-audio-api](https://github.com/ircam-ismm/node-web-audio-api).

Actually, from your example code and `import` statement, it seems that you are using the [`web-audio-api`](https://www.npmjs.com/package/web-audio-api) package which indeed appears unmaintained since quite a long time... but their repository is [there](https://github.com/audiojs/web-audio-api) so the issue should be there too.
