### ISSUE TITLE
Add DecodeAudioData to AudioContext

### ISSUE THREAD

**Issue by Jerboas86** [orottier/web-audio-api-rs#42]
The implementation should follow this part of the specification (see [DecodeAudioData](https://www.w3.org/TR/webaudio/#dom-baseaudiocontext-decodeaudiodata))

**Comment by orottier** [comment]
How would you translate it to rust primitives? Maybe make it generic over `R: Read`. I don't think the project is mature enough to start with async functionality, let's put that burden on the users of this lib for now

**Comment by b-ma** [comment]
- use https://github.com/pdeljanov/Symphonia for decoding?
- resample decoded audio to current `AudioContext` sample rate

**Comment by orottier** [comment]
I'm contemplating to pull this in before the v1.0 release. Bringing in Symphonia will probably change the way we expose the Wav/OggVorbis-decoder now (we may even drop them in favour of a more generic MediaElement constructor).

I'm self assinging for now and see where it takes us!

**Comment by orottier** [comment]
Implemented in #82

**Comment by b-ma** [comment]
Hum, I have the impression there are some issues with the new decoding: 

- in `sample.wav` there is a click at end of the file that was not there before (you can ear it in the `trigger_soundfile` example)
- in `sample.ogg` there are some weird artifacts everywhere (that may be due to resampling because the file sample rate - 32kHz apparently - does not match my system sample rate).

I have also this error popping up sometimes that I don't think I have seen before (not always tough, I will try to find out in which case it appears):
```
[2022-01-05T14:32:50Z ERROR web_audio_api::media::decoding] next packet err IoError(Custom { kind: UnexpectedEof, error: "end of stream" })
```

I will also create a small test/example with several encodings of `sample.wav` created with `ffmpeg` or Audacity (so we are pretty sure the encoding is clean) to help investigate that

**Comment by orottier** [comment]
Interesting, nice catch!
I will investigate the click from the wav file. I copied most of the decoding from https://github.com/pdeljanov/Symphonia/blob/master/symphonia/examples/basic-interleaved.rs but I may have made a mistake.
The ringing in sample.ogg may be due to the low quality `Resampler` that is currently included in src/buffer.rs, let's find out

**Comment by orottier** [comment]
The error is a known/accepted problem: https://github.com/pdeljanov/Symphonia/issues/62 and we handle it correctly this way (I should improve the log message though)

The search for the click continues

**Comment by b-ma** [comment]
Just to let you know I have made a small test here https://github.com/b-ma/web-audio-api-rs/tree/test/decoding 

I exported the encoded the `sample.wav` file with Audacity at 44100Hz in `wav`, `flac`, `mp3` and `ogg` and except for the `wav` file the other ones sound quite good I think (no obvious artefacts at least).
- the `mp3` is a bit longer than the others but that might be due to encoding and/or decoding. I will do another export with `ffmpeg` tomorrow that I know puts the correct header to avoid silence in the beginning of the file if the decoder is fine (I don't remember if Audacity is ok on that point).
- didn't try Opus yet, and `aiff` fails at decoding (which is probably expected I guess)
- an interesting point is that `wav` and `flac` don't have the same number of samples, which is really strange I think, as they should both be lossless formats... as `wav` is the longer one, that's where the click might live...
```
> --------------------------------
> reading file "samples/sample.wav"
> duration 3.2248526077097504
> num samples 142216
> --------------------------------
> reading file "samples/sample.flac"
> duration 3.2241950113378683
> num samples 142187
> --------------------------------
> reading file "samples/sample.mp3"
> duration 3.2653061224489797
> num samples 144000
> --------------------------------
> reading file "samples/sample.ogg"
> duration 3.2435374149659864
> num samples 143040
```

A can make a PR if you think it worth it, but maybe you don't want all these audio files in the source code, let me know

**Comment by orottier** [comment]
Thanks, very helpful. Please check in the assets, we can always prune them later

**Comment by b-ma** [comment]
Ok, quite funny fact, I just tried re-encoding the sample to `wav` from the `flac` version (using `ffmpeg`) and (suspens...) it sounds good and the number of samples is consistent:

```
> --------------------------------
> reading file "samples/sample-2.wav"
> duration 3.2241950113378683
> num samples 142187
> --------------------------------
> reading file "samples/sample.flac"
> duration 3.2241950113378683
> num samples 142187
```

...more extreme funny fact, I re-encoded the file in `wav` from itself (w/ ffmpeg again) and... it's good too!

```
> --------------------------------
> reading file "samples/sample-3.wav"
> duration 3.2241950113378683
> num samples 142187
> --------------------------------
> reading file "samples/sample.flac"
> duration 3.2241950113378683
> num samples 142187
```

What is quite strange here is that initial `sample.wav` has been exported from Audacity when I applied a small fadeout at the end, and that it was properly decoded by `hound` (would be interesting to see how many samples `hound` finds in that file...). I will try to export another .wav file from Audacity to check if the same problem happens

Anyway, if it's an issue I guess we can quite safely consider it is more a Symphonia issue.

> Please check in the assets, we can always prune them later

ok cool, I will clean my example, harmonize all paths to the `samples` directory and make a PR then

**Comment by orottier** [comment]
After some investigation I think it is Symphonia that leaves some stray samples in the last decoded chunk. Probably there is a buffer reused in every decoding step but not properly truncated in the last chunk. I will check my work and raise an issue upstream.

**Comment by b-ma** [comment]
ok, I will leave both `faulty` and `good` files in the PR, maybe it can help to track down the issue (my impression is that there is something wrong or not properly parsed in the file header too)

**Comment by orottier** [comment]
All fixed now
