### ISSUE TITLE
Issue with NodeCollection

### ISSUE THREAD

**Issue by b-ma** [orottier/web-audio-api-rs#468]
Just had this issue

```
thread '<unnamed>' panicked at /web-audio-api-rs/src/render/node_collection.rs:96:32:
Index 45 for dropped Node in NodeCollection
```

I really don't know where it comes from, the app is rather complex and dynamic. I will try to investigate next week and see if I can come with a minimal failing test bed

**Comment by orottier** [comment]
Thanks, that would be very helpful.
Does your graph involve nodes connecting to audio params? E.g. constant src -> playback rate -> buffer src? I just realized this may trigger an issue with dynamic lifetimes

In any case I should improve the error message in these rare cases because the current message is not helpful. (Track caller does not appear to work on trait methods)

**Comment by orottier** [comment]
Marking this one solved. For now..

**Comment by b-ma** [comment]
> For now..

Huhu :)
