### ISSUE TITLE
How to deal with related web concepts (<audio> element, WebRTC, MediaCapture)

### ISSUE THREAD

**Issue by orottier** [orottier/web-audio-api-rs#84]
As mentioned in #82:

To be fair I'm struggling a bit with the 'boundaries' of the Web Audio API also in other cases. For #77 I was playing around with microphone input and playback and realized I needed to have something like https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder

There are a few conflicting goals:
- stay as close as possible to the spec (as that is the unique selling point of this project, provide the comfort of not learning a new API when coming from a web background)
- leverage all the power of rust (no nullables, no exceptions, use ownership etc)
- create a small library (it's a lot of work already in its current state), versus:
- include related APIs (https://w3c.github.io/mediacapture-main/ https://w3c.github.io/webrtc-pc/ https://html.spec.whatwg.org/multipage/media.html#the-audio-element )
- or include include a few intefaces acting as building blocks (the `MediaStream` trait)

I will create a separate issue for this. It's probably best to steer away from names such as `MediaStream` and `MediaElement` because as you pointed out these are different from the w3c specs. I do think we should include them in the library because you would need them in many applications anyway

_Originally posted by @orottier in https://github.com/orottier/web-audio-api-rs/pull/82#discussion_r778097042_

**Comment by orottier** [comment]
I have added this to the v1.0 checklist. We don't need to have an allround solution but we do need to put some thought in keeping/renaming/dropping the MediaStream trait, the MediaElement en the Microphone input

**Comment by b-ma** [comment]
I think a quite clean tradeoff could be:

Keep the `Microphone`, `MediaElement` and `MediaStream` (with eventual renaming: `AudioPlayer` ? `AudioElement` ? `WebAudioStream` ?)

- I really think that the `Microphone` and `MediaElement` are really nice to have at hand without having to install another lib and write manually all the pipes and interfaces for most usage. And if I understand well if one needs to go beyond these helpers, the `MediaStream` trait makes it possible.

- As all these abstraction are in the `media` namespace (I still think `extra` would be more clear but that's really not a big deal), this is really simple to document and explain that they are provided to be helpful but actually belong to other Web Specs and do not aim at implementing all the features from these specs. 

- If someone wants to implement one of these APIs with all their features, the interface between the two libs seems possible thanks to the `MediaStream` trait, so that's really nice

- For the naming issues, two points taken into account I guess, 1. the term `Media` generally concerns both audio and video so it might be confusing, 2. `MediaStream` is maybe too generic and not enough meaningful if another lib should implement it to provide compatibility with the crate.

- A kind of simple `MediaRecorder` would be really nice to have for sure, but again as long it does the minimal useful work, I don't think the whole spec needs to be implemented neither. 

- To be short, the important thing here in my opinion is to propose an API that allows to interface properly with other libs that would seek to implement other specifications in a more precise manner (from what I understand this is almost, if not already, the case), and a really good point of these helpers, beyond the fact they are helpful, is that they show that it is possible, so all good :)

The only real inconstancy with the WebAudio spec I see so far, concerns the `MediaElementAudioSourceNode` which should be implemented as a kind of "sink" of the `MediaElement` rather than an `AudioScheduledSourceNode`. 

- From what I see being closer to the Web APIs here would just (maybe this "just" is a bit optimistic...) mean moving the `start`, `stop` and `loop`  abilities (i.e. `scheduler` and `controller`) from the `MediaElementAudioSourceNode` to the `MediaElement` (that doesn't need to work beyond block rate I think)

- The `MediaElementAudioSourceNode` would thus be really close to the `MediaStreamAudioSourceNode`, just acting as a "dumb" node that make sure the sample rate is right (and maybe, to be confirmed, is dropped when its source is closed or ended).

**Comment by orottier** [comment]
Thanks for the elaborate reply. I think your suggestions make a lot of sense.
Indeed adding an `extras` mod will properly give off the messages that this is outside the spec and should be taken for granted.
I will start renaming and moving around some structs

**Comment by b-ma** [comment]
Assigning myself, as it's actually very related w/ `AudioScheduledSourceNode` and making `Scheduler` and `Controller` private

**Comment by b-ma** [comment]
Interesting collection of JS examples showing the I/O interfaces of the WebAudio API with WebRTC (e.g. MediaElementSource, MediaStreamSource and MediaStreamDestination)

[https://dvcs.w3.org/hg/audio/raw-file/tip/webaudio/webrtc-integration.html](https://dvcs.w3.org/hg/audio/raw-file/tip/webaudio/webrtc-integration.html)

**Comment by b-ma** [comment]
to be continued...

**Comment by orottier** [comment]
I think we have mostly fleshed this out.
- MediaElement is postponed for now
- MediaRecorder is trivial to implement for users now we have `createMediaStreamDestination`
- AudioScheduledSourceNode is spec compliant

Closing this, please re-open if anyone disagrees!
